version: '3.9'

services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${HOST_DB_PORT}:${DB_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: python run.py
    ports:
      - "${HOST_APP_PORT}:${APP_PORT}"
    depends_on:
      - db
    environment:
      FLASK_ENV: ${FLASK_ENV}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
    volumes:
      - .:/app

  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    environment:
      - EMBEDDING_MODEL_NAME=${OLLAMA_EMBEDDING_MODEL}
      - LLM_MODEL_NAME=${OLLAMA_LLM_MODEL}
    ports:
      - "${HOST_OLLAMA_PORT}:${OLLAMA_PORT}"
    volumes:
      - ollama-models:/root/.ollama
    restart: unless-stopped



volumes:
  postgres_data:
  ollama-models: