"""Added version column for optimistic locking

Revision ID: 172ef648eea7
Revises: 1a1b35c4c659
Create Date: 2025-08-13 13:18:09.274015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '172ef648eea7'
down_revision = '1a1b35c4c659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f('idx_events_embedding_cosine'), postgresql_with={'lists': '100'}, postgresql_using='ivfflat')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('version')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_events_embedding_cosine'), ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
        batch_op.drop_column('version')

    # ### end Alembic commands ###
