"""Added embedding column and cosine index

Revision ID: 1a1b35c4c659
Revises: 276758c52645
Create Date: 2025-08-13 11:21:18.073813

"""
from alembic import op
import sqlalchemy as sa
import pgvector
from pgvector.sqlalchemy.vector import VECTOR

# revision identifiers, used by Alembic.
revision = '1a1b35c4c659'
down_revision = '276758c52645'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        # enable pgvector in this database if not already enabled
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_email_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.execute("""
                        DO $$
                        BEGIN
                          IF NOT EXISTS (
                            SELECT 1
                            FROM   pg_class c
                            JOIN   pg_namespace n ON n.oid = c.relnamespace
                            WHERE  c.relname = 'idx_events_embedding_cosine'
                              AND n.nspname = 'public'
                          ) THEN
                            CREATE INDEX idx_events_embedding_cosine
                            ON events USING ivfflat (embedding vector_cosine_ops)
                            WITH (lists = 100);
                          END IF;
                        END
                        $$;
                    """)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_unique_constraint(batch_op.f('user_email_key'), ['email'])

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('embedding')

    # ### end Alembic commands ###
