"""added versioning for optimistic locking in user and event tables

Revision ID: 6d4a99a4b86f
Revises: b53c7fb4833a
Create Date: 2025-08-07 15:27:51.884770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d4a99a4b86f'
down_revision = 'b53c7fb4833a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('version')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('version')

    # ### end Alembic commands ###
