"""Added vector embedding to event table

Revision ID: b53c7fb4833a
Revises: 276758c52645
Create Date: 2025-08-05 19:40:19.282469

"""
import pgvector
from alembic import op
import sqlalchemy as sa
from app.configuration.config import Config
from pgvector import Vector


# revision identifiers, used by Alembic.
revision = 'b53c7fb4833a'
down_revision = '276758c52645'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(Config.UNIFIED_VECTOR_DIM), nullable=True))
        op.execute("""
                DO $$
                BEGIN
                  IF NOT EXISTS (
                    SELECT 1
                    FROM   pg_class c
                    JOIN   pg_namespace n ON n.oid = c.relnamespace
                    WHERE  c.relname = 'idx_events_embedding_l2'
                      AND n.nspname = 'public'
                  ) THEN
                    CREATE INDEX idx_events_embedding_l2
                    ON events USING ivfflat (embedding vector_l2_ops)
                    WITH (lists = 100);
                  END IF;
                END
                $$;
            """)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_email_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_unique_constraint(batch_op.f('user_email_key'), ['email'])

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('embedding')

    # ### end Alembic commands ###
