"""Updated event field parameters

Revision ID: bf761c1ebc4a
Revises: 1bde71ea3935
Create Date: 2025-08-19 14:16:37.115249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf761c1ebc4a'
down_revision = '1bde71ea3935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
