from typing import List, Dict, Protocol

Message = Dict[str, str]  # {"role": "user"|"assistant"|"system", "content": "..."}

class ChatHistoryRepository(Protocol):
    def get(self, key: str) -> List[Message]: ...
    def set(self, key: str, messages: List[Message]) -> None: ...
    def append(self, key: str, role: str, content: str) -> None: ...
